### ISSUE TITLE
Backslash/semicolon/octothorpe escaping

### ISSUE THREAD

**Issue by xuhdev** [editorconfig/editorconfig-vote#5]
In property values (outside globs inside brackets), should we add backslash/semicolon/octothorpe escaping into EditorConfig specification? **Please vote by commenting below: yes or no only. Voting will be closed at the end of May 6**.

Related/discussion issue editorconfig/editorconfig-core-test#24

@editorconfig/board-member cc @rakus

**Comment by jednano** [comment]
yes

**Comment by florianb** [comment]
I stay neutral on this for two reasons:

1. I'd like to vote "no" because i think the problem is we didn't explicitly specify yet how custom properties may be used with the editorconfig. And we didn't specify explicitly the editorconfig-fileformat, ini files itself aren't specified and the behavior of the reference parser (`ConfigParser`) depends on modal parameters. But i don't want to stay in the way of @rakus implementation.

2. I'd also like to vote yes, since we become a little more explicit about the handling of values. But i also think the escaping of octothorpes, semicolons and backslashes is by far not enough to allow a secure and complete serialization of valid UTF-8 strings.

I'd enjoy to see if this could lead to a discussion how a ini-file is formally defined and how people may safely add custom properties.

**Comment by ppalaga** [comment]
yes

**Comment by sindresorhus** [comment]
no

Because I rather see it done properly by defining a formal grammar instead of just a quick fix.

**Comment by rakus** [comment]
On one hand I think the vote is to early, on the other hand it might be the spark to start the discussion about a formally defined file format.

I personally I tend to vote "No" as I think that the file format should be as simple as possible.

Anyway, I agree with @sindresorhus  and @florianb: We need a strong formal specification and I'm willing to contribute.

PS: I'm not implementing something new, I just implemented a [Vim editorconfig plugin](https://github.com/rakus/vimscript-editorconfig). While implementing I missed a formal specification.

**Comment by Mpdreamz** [comment]
no, 

I too would like a more in depth spec including learning what INI does here.
Would also like to learn how common the case is and whether we can simply mandate comments being only available when on a line of their own.

**Comment by xuhdev** [comment]
The conclusion is **no**. Closed
